baseURL = "http://lillianzhang.github.io/nianrongliang"
languageCode = "en-us"
title = "Nianrong Liang, CPA"
theme="amp"
copyright = "© 2017 Nianrong Liang"
canonifyurls = true
publishDir = "docs"

[params]
  description = "Your Site description for top page" #optional

# optional
[social]
  twitter = "Your Twitter Name"
  github = "Your Github Name"
  facebook = "Your facebook Name"
  gplus = "Your Google+ profile name"
  linkedin = "Your LinkedIn Name"
